// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFSoK7YI-yGv92O_SO5XzCcUkL7rkC9UI',
    appId: '1:867216782979:web:f54c63a79dbf625c87cdb6',
    messagingSenderId: '867216782979',
    projectId: 'jei-lms-app',
    authDomain: 'jei-lms-app.firebaseapp.com',
    storageBucket: 'jei-lms-app.appspot.com',
    measurementId: 'G-88HV68L0H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCsJ6iBJ2mJ6wgFjJL8wCPi0KxrnW_fV0',
    appId: '1:867216782979:android:f28efa642d25a85a87cdb6',
    messagingSenderId: '867216782979',
    projectId: 'jei-lms-app',
    storageBucket: 'jei-lms-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5P63cZmusR0cAFeIsCrCYCkuvbuMdlsQ',
    appId: '1:867216782979:ios:f88562122d4029d687cdb6',
    messagingSenderId: '867216782979',
    projectId: 'jei-lms-app',
    storageBucket: 'jei-lms-app.appspot.com',
    iosBundleId: 'com.example.lmsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5P63cZmusR0cAFeIsCrCYCkuvbuMdlsQ',
    appId: '1:867216782979:ios:4115f294005119ab87cdb6',
    messagingSenderId: '867216782979',
    projectId: 'jei-lms-app',
    storageBucket: 'jei-lms-app.appspot.com',
    iosBundleId: 'com.example.lmsApp.RunnerTests',
  );
}
